config/routes.rb
Rails.application.routes.draw do
  get 'poker_help/index'

  get 'poker_stat/index'

  get 'games/new'

  get 'games/index'

  get 'games/show'

  get 'games/edit'

  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
load "#{Rails.root}/lib/assets/DrawPokerLogic.rb"
include DrawPokerLogic
  def new

    @game=Game.new
      ## deals hand to computer, saves its values and rank to the database 
      initial_computer_hand_array=deal(5)
      @game.initial_computer_hand=to_string(initial_computer_hand_array)
      @game.initial_computer_hand_rank=determine_hand(initial_computer_hand_array)
   
      ## deals hand to player, saves its values and rank to the database
      initial_player_hand_array=deal(5,initial_computer_hand_array)
      @game.initial_player_hand=to_string(initial_player_hand_array)
      @game.initial_player_hand_rank=determine_hand(initial_player_hand_array)

      @game.save


      respond_to do |format|
        format.html
        format.js { render :action => 'new' }

      end
  end

  def index
  end

  def show
      @game=Game.find(params[:game])
      initial_hand_array=@game.initial_player_hand.split(',')
      @suggestedDiscard=automatic_discard(initial_hand_array)

      respond_to do |format|
        format.js { render :action => 'show' }
      end
  end

  def edit
    @game=Game.find(params[:game])
    player_discard_selection=[]
    discard_params=params[:discard]
    if discard_params
     discard_params.each do |x|
     player_discard_selection << x.to_i
     end
    end

    
    if @game.winner == nil
    initial_player_hand_array=@game.initial_player_hand.split(",")
    initial_computer_hand_array=@game.initial_computer_hand.split(",")
    cards_in_play = initial_player_hand_array + initial_computer_hand_array


    computer_discard_array=discard(initial_computer_hand_array,automatic_discard(initial_computer_hand_array))
    @game.computer_discard=to_string(computer_discard_array)
    ####player discard selection will be an array from the screen instead of the automatic discard
    player_discard_array=discard(initial_player_hand_array,player_discard_selection)
    @game.player_discard=to_string(player_discard_array)

    new_computer_cards=deal(computer_discard_array.length,cards_in_play)
    final_computer_hand_array=new_computer_cards + initial_computer_hand_array
    cards_in_play += new_computer_cards
    @game.final_computer_hand=to_string(final_computer_hand_array)

    final_player_hand_array=deal(player_discard_array.length,cards_in_play) +  initial_player_hand_array
    @game.final_player_hand=to_string(final_player_hand_array)

    @game.winner = compare_hands(final_computer_hand_array,final_player_hand_array)

    @game.final_player_hand_rank=determine_hand(final_player_hand_array)
    @game.final_computer_hand_rank=determine_hand(final_computer_hand_array)

    @game.save

      respond_to do |format|
        format.js { render :action => 'edit' }
      end
    end

  end
end

app/controllers/poker_help_controller.rb
class PokerHelpController < ApplicationController
  def index
  end
end

app/controllers/poker_stat_controller.rb
class PokerStatController < ApplicationController
  def index
      respond_to do |format|
        format.html
        format.js {}
      end


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/poker_help_helper.rb
module PokerHelpHelper
end

app/helpers/poker_stat_helper.rb
module PokerStatHelper
end

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

app/views/games/edit.js.erb
function faceCardNumber(cardString) {
 if (cardString=="ACE"){
   var returnValue="1";
} else if (cardString=="JACK"){
   var returnValue="11";
} else if (cardString=="QUEEN"){
   var returnValue="12";
} else if (cardString=="KING"){
   var returnValue="13";
}
 return returnValue;
}

function findCard(cardString) {
 if(Number(cardString.split(" ")[0])){
   var cardNumber = cardString.split(" ")[0];
} else {
   var cardNumber = faceCardNumber(cardString.split(" ")[0]);
}
 var suitLetter = cardString.split(" ")[2][0];
 var returnValue = "/" + cardNumber + suitLetter + ".svg";
 return returnValue;
}



var playerHand=("<%=@game.final_player_hand%>");
var playerHandArray=playerHand.split(",");
$("#cp0").attr('src',findCard(playerHandArray[0]));
$("#cp1").attr('src',findCard(playerHandArray[1]));
$("#cp2").attr('src',findCard(playerHandArray[2]));
$("#cp3").attr('src',findCard(playerHandArray[3]));
$("#cp4").attr('src',findCard(playerHandArray[4]));
$("#p0").css("background-color","rgba(0,0,0,0)");
$("#p1").css("background-color","rgba(0,0,0,0)");
$("#p2").css("background-color","rgba(0,0,0,0)");
$("#p3").css("background-color","rgba(0,0,0,0)");
$("#p4").css("background-color","rgba(0,0,0,0)");
var computerHand=("<%=@game.final_computer_hand%>");
var computerHandArray=computerHand.split(",");
$("#cc0").attr('src',findCard(computerHandArray[0]));
$("#cc1").attr('src',findCard(computerHandArray[1]));
$("#cc2").attr('src',findCard(computerHandArray[2]));
$("#cc3").attr('src',findCard(computerHandArray[3]));
$("#cc4").attr('src',findCard(computerHandArray[4]));
$(".computerRank").text("<%=@game.final_computer_hand_rank%>");
$(".playerRank").text("<%=@game.final_player_hand_rank%>")
var winner=("<%=@game.winner%>");
if (winner == "player wins") {
$(".playerWinner").text("you won!!");
} else if (winner == "computer wins") {
$(".computerWinner").text("the computer won!!");
} else
{
$(".playerWinner").text("it's a tie!!");
$(".computerWinner").text("it's a tie!!");
}
$(".game").val("");

app/views/games/index.html.erb
<div class="helpMenu"> <%= link_to "Help", poker_help_index_path %> </div>
<div class="statisticsMenu"> <%= link_to "Statistics", poker_stat_index_path %> </div>



<h1>5 Card Draw</h1>



<div class="menus">
<div class="computerRank"></div>
<div class="computerWinner"></div>
</div>
<table>
  <tr>
    <td id="c0"> <img id="cc0" src="/card.png" width="100" height="150">  </td>
    <td id="c1"> <img id="cc1" src="/card.png" width="100" height="150">  </td>
    <td id="c2"> <img id="cc2" src="/card.png" width="100" height="150">  </td>
    <td id="c3"> <img id="cc3" src="/card.png" width="100" height="150">  </td>
    <td id="c4"> <img id="cc4" src="/card.png" width="100" height="150">  </td>
  </tr>
  <tr>
    <td onclick="colorToggle(this)" id="p0"><img id="cp0" src="/card.png" width="10" height="150"> </td>
    <td onclick="colorToggle(this)" id="p1"><img id="cp1" src="/card.png" width="100" height="150">  </td>
    <td onclick="colorToggle(this)" id="p2"><img id="cp2" src="/card.png" width="100" height="150">  </td>
    <td onclick="colorToggle(this)" id="p3"><img id="cp3" src="/card.png" width="100" height="150">  </td>
    <td onclick="colorToggle(this)" id="p4"><img id="cp4" src="/card.png" width="100" height="150">  </td>
  </tr>
</table>
<div class="playerWinner"></div>
<div class="playerRank"></div>

<button onclick="newGame()"> New Game </button>
<button class="game" val ="" onclick="discard(this.value)"> Discard </button>
<button onclick="suggestDiscard()"> Suggest Discard </button>

app/views/games/index.js.erb
console.log("this is the index.js.erb file");

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/new.js.erb
function faceCardNumber(cardString) {
 if (cardString=="ACE"){
   var returnValue="1";
} else if (cardString=="JACK"){
   var returnValue="11";
} else if (cardString=="QUEEN"){
   var returnValue="12";
} else if (cardString=="KING"){
   var returnValue="13";
}
 return returnValue;
}

function findCard(cardString) {
 if(Number(cardString.split(" ")[0])){
   var cardNumber = cardString.split(" ")[0];
} else {
   var cardNumber = faceCardNumber(cardString.split(" ")[0]);
}
 var suitLetter = cardString.split(" ")[2][0];
 var returnValue = "/" + cardNumber + suitLetter + ".svg";
 return returnValue;
}



$(".game").val(<%=@game.id%>);
var playerHand=("<%=@game.initial_player_hand%>");
var playerHandArray=playerHand.split(",");
$("#p0").css("background-color","rgba(0,0,0,0)");
$("#p1").css("background-color","rgba(0,0,0,0)");
$("#p2").css("background-color","rgba(0,0,0,0)");
$("#p3").css("background-color","rgba(0,0,0,0)");
$("#p4").css("background-color","rgba(0,0,0,0)");
$("#cp0").attr('src',findCard(playerHandArray[0]));
$("#cp1").attr('src',findCard(playerHandArray[1]));
$("#cp2").attr('src',findCard(playerHandArray[2]));
$("#cp3").attr('src',findCard(playerHandArray[3]));
$("#cp4").attr('src',findCard(playerHandArray[4]));
$("#cc0").attr('src',"/card.png");
$("#cc1").attr('src',"/card.png");
$("#cc2").attr('src',"/card.png");
$("#cc3").attr('src',"/card.png");
$("#cc4").attr('src',"/card.png");
$(".computerRank").text("");
$(".playerRank").text("");
$(".playerWinner").text("");
$(".computerWinner").text("");

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/games/show.js.erb
var discardArray = <%= @suggestedDiscard %>;
$("#p0").css("background-color","rgba(0,0,0,0)");
$("#p1").css("background-color","rgba(0,0,0,0)");
$("#p2").css("background-color","rgba(0,0,0,0)");
$("#p3").css("background-color","rgba(0,0,0,0)");
$("#p4").css("background-color","rgba(0,0,0,0)");
if (discardArray.includes(0)){
$("#p0").css("background-color","rgb(255, 200, 0)");
}
if (discardArray.includes(1)){
$("#p1").css("background-color","rgb(255, 200, 0)");
}
if (discardArray.includes(2)){
$("#p2").css("background-color","rgb(255, 200, 0)");
}
if (discardArray.includes(3)){
$("#p3").css("background-color","rgb(255, 200, 0)");
}
if (discardArray.includes(4)){
$("#p4").css("background-color","rgb(255, 200, 0)");
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrawPoker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/poker_help/index.html.erb
<div class="gameMenu"> <%= link_to "Return to Game", games_index_path %> </div>
<h1>Help</h1>

<h4>Playing the Game</h4>
<div class="helpText">
<p>You can find a three button interface, right below the table of cards.
<button class="example">New Game</button>
<button class="example">Discard</button>
<button class="example">Suggest Discard</button>
</p>
<p>
<button>New Game</button><br>
This will start a new game! If you haven't finished the hand on the screen it will disappear <strong>forever!</strong> You'll never know what might have happened!
</p>

<p>
<button>Discard</button><br>
You can pick which cards you'd like to discard! Just click on them and they'll develop a yellow glow. If you change your mind, click it again they'll go back to normal. Once you've decided which cards you'd like to get rid of, click the Discard button and they'll disappear <strong>forever!</strong> They'll be replaced with new cards. If you don't click any cards, the computer assumes you just want to keep all of them. Maybe you have a really great hand! At this point you'll get to see the computer's cards. You'll know who won! I hope you won! But if you didn't just click on New Game and try again!
</p>
<p>
<button>Suggest Discard</button><br>
Maybe you're not sure which cards you'd like to discard! Click on this button and the computer will suggest which cards you should get rid of. It'll turn them yellow. You don't have to accept the computer's suggestion! Click on a selected card to keep it, or click on an additional card to get rid of that one too. After you've made up your mind, click on Discard and they'll disappear <strong>forever!</strong>
</p>
</p>
</div>
<br>
<h4>Rules of Poker</h4>
<div class="helpText">
<p>
Have you played Poker before? It's fun! There are many variations of the game. This one is called Five Card Draw. You and the computer both get five cards to start with. You look them over and decide which you'd like to keep and which you'd like to discard. After your discard, each of the discarded cards are replaced and you compare your hand to the computer's and see whose is higher.
</p>
<p>
The table below shows the rankings of the hands. The higher up the table, the higher the rank. If you and the computer have the same hand, it looks to see who has the highest cards. So if you have a flush with an Ace, that will beat a flush whose high card is a Jack. If you have pairs, three of a kind, or four of a kind, it checks in the matched cards first. If those are the same, then the additional cards are checked to see which is higher. Every now and then you and the computer might have the exact same cards. Then it's a tie! That's wild! It doesn't happen often. I ran about 5,000 simulation games when I was building this site, in fact, and it never happened. But it could! If it happens to you, you must be lucky!
</p>
<p>
In case you're wondering how you know which card is higher, I'll explain! The number cards, 2-10, have the value listed on their face. Jacks are worth 11, Queens are worth 12 and Kings are worth 13. Aces are a little different. They can be worth 1 or 14, depending on the rest of your hand. Usually, you'll want them to be worth 14. But, for example, if you have Ace, 2, 3, 4 and 5, you'd want the Ace to be worth 1. You'll have a straight. That's a pretty good hand.
</p>
</div>
<div>
<table>
<caption>Value of Poker Hands</caption>
<tr><th>Hand</th><th>Description</th></tr>
<tr><td>Royal Flush</td><td>Ace,King,Queen,Jack,10 all of the same suit</td></tr>
<tr><td>Straight Flush</td><td>Cards in a consecutive sequence all of the same suit</td></tr>
<tr><td>Four of a Kind</td><td>Four cards all of the same rank</td></tr>
<tr><td>Full House</td><td>Three of a kind and a pair</td></tr>
<tr><td>Flush</td><td>Ace,King,Queen,Jack,10 all of the same suit</td></tr>
<tr><td>Straight</td><td>Cards in a consecutive sequence</td></tr>
<tr><td>Three of a Kind</td><td>Three cards all of the same rank</td></tr>
<tr><td>Two Pairs</td><td>Two different pairs of cards with the same rank </td></tr>
<tr><td>One Pair</td><td>Two cards of the same rank</td></tr>
<tr><td>Nothing</td><td>A hand with none of the combinations, worth as much as its highest card</td></tr>
</table>
</div>


if you have any more questions or concerns or if you just want to say hi, you can <%= mail_to "ctballentine@gmail.com", "Email me!" %>

app/views/poker_stat/index.html.erb
<div class="gameMenu"> <%= link_to "Return to Game", games_index_path %> </div>
<h1>Statistics</h1>

<div><table>
  <tr><th>Player Wins</th><th>Computer Wins</th></tr>
  <tr><td class=playerWins></td><td class=computerWins></td></tr>
  <tr><td class=playerWinsPercent></td><td class=computerWinsPercent></td></tr>
</table></div>
<div><table>
  <tr><th>Hands</th><th>Number of Occurances</th><th>Percentage of Occurances</th><th>Percentage of Times Hand is a Winner</th></tr>
  <tr><td>Royal Flush</td><td class=royalFlushNumber></td><td class=royalFlushPer></td><td class=royalFlushPerWin></td></tr>
  <tr><td>Straight Flush</td><td class=straightFlushNumber></td><td class=straightFlushPer></td><td class=straightFlushPerWin></td></tr>
  <tr><td>Four of a Kind</td><td class=fourKindNumber></td><td class=fourKindPer></td><td class=fourKindPerWin></td></tr>
  <tr><td>Full House</td><td class=fullHouseNumber></td><td class=fullHousePer></td><td class=fullHousePerWin></td></tr>
  <tr><td>Flush</td><td class=flushNumber></td><td class=flushPer></td><td class=flushPerWin></td></tr>
  <tr><td>Straight</td><td class=straightNumber></td><td class=straightPer></td><td class=straightPerWin></td></tr>
  <tr><td>Three of a Kind</td><td class=threeKindNumber></td><td class=threeKindPer></td><td class=threeKindPerWin></td></tr>
  <tr><td>Two Pairs</td><td class=twoPairNumber></td><td class=twoPairPer></td><td class=twoPairPerWin></td></tr>
  <tr><td>One Pair</td><td class=onePairNumber></td><td class=onePairPer></td><td class=onePairPerWin></td></tr>
  <tr><td>Nothing</td><td class=nothingNumber></td><td class=nothingPer></td><td class=nothingPerWin></td></tr>
</table></div>
<div></div>

app/views/poker_stat/index.js.erb
$(".computerWins").text(<%=Game.where(winner: 'computer wins').length%>);
$(".playerWins").text(<%=Game.where(winner: 'player wins').length%>);
$(".computerWinsPercent").text(<%=(Game.where(winner: 'computer wins').length.to_f/Game.where.not(winner: nil).length*100).round(2).to_s %> + "%");
$(".playerWinsPercent").text(<%=(Game.where(winner: 'player wins').length.to_f/Game.where.not(winner: nil).length*100).round(2)%> + "%");
$(".royalFlushNumber").text(<%=Game.where(final_player_hand_rank: "royal flush").length + Game.where(final_computer_hand_rank: "royal flush").length%>);


$(".royalFlushPer").text(<%=(((Game.where(final_player_hand_rank: "royal flush").length.to_f + Game.where(final_computer_hand_rank: "royal flush").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".royalFlushPerWin").text(<%= ((Game.where(final_player_hand_rank: "royal flush").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "royal flush").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "royal flush").length + Game.where(final_computer_hand_rank: "royal flush").length.to_f)*100).round(2).to_s %> + "%");

$(".straightFlushNumber").text(<%=Game.where(final_player_hand_rank: "straight flush").length + Game.where(final_computer_hand_rank: "straight flush").length%>);
$(".straightFlushPer").text(<%=(((Game.where(final_player_hand_rank: "straight flush").length.to_f + Game.where(final_computer_hand_rank: "straight flush").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".straightFlushPerWin").text(<%= ((Game.where(final_player_hand_rank: "straight flush").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "straight flush").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "straight flush").length + Game.where(final_computer_hand_rank: "straight flush").length.to_f)*100).round(2).to_s %> + "%");


$(".fourKindNumber").text(<%=Game.where(final_player_hand_rank: "four of a kind").length + Game.where(final_computer_hand_rank: "four of a kind").length%>);
$(".fourKindPer").text(<%=(((Game.where(final_player_hand_rank: "four of a kind").length.to_f + Game.where(final_computer_hand_rank: "four of a kind").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".fourKindPerWin").text(<%= ((Game.where(final_player_hand_rank: "four of a kind").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "four of a kind").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "four of a kind").length + Game.where(final_computer_hand_rank: "four of a kind").length.to_f)*100).round(2).to_s %> + "%");


$(".fullHouseNumber").text(<%=Game.where(final_player_hand_rank: "full house").length + Game.where(final_computer_hand_rank: "full house").length%>);
$(".fullHousePer").text(<%=(((Game.where(final_player_hand_rank: "full house").length.to_f + Game.where(final_computer_hand_rank: "full house").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".fullHousePerWin").text(<%= ((Game.where(final_player_hand_rank: "full house").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "full house").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "full house").length + Game.where(final_computer_hand_rank: "full house").length.to_f)*100).round(2).to_s %> + "%");


$(".flushNumber").text(<%=Game.where(final_player_hand_rank: "flush").length + Game.where(final_computer_hand_rank: "flush").length%>);
$(".flushPer").text(<%=(((Game.where(final_player_hand_rank: "flush").length.to_f + Game.where(final_computer_hand_rank: "flush").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".flushPerWin").text(<%= ((Game.where(final_player_hand_rank: "flush").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "flush").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "flush").length + Game.where(final_computer_hand_rank: "flush").length.to_f)*100).round(2).to_s %> + "%");


$(".straightNumber").text(<%=Game.where(final_player_hand_rank: "straight").length + Game.where(final_computer_hand_rank: "straight").length%>);
$(".straightPer").text(<%=(((Game.where(final_player_hand_rank: "straight").length.to_f + Game.where(final_computer_hand_rank: "straight").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".straightPerWin").text(<%= ((Game.where(final_player_hand_rank: "straight").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "straight").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "straight").length + Game.where(final_computer_hand_rank: "straight").length.to_f)*100).round(2).to_s %> + "%");


$(".threeKindNumber").text(<%=Game.where(final_player_hand_rank: "three of a kind").length + Game.where(final_computer_hand_rank: "three of a kind").length%>);
$(".threeKindPer").text(<%=(((Game.where(final_player_hand_rank: "three of a kind").length.to_f + Game.where(final_computer_hand_rank: "three of a kind").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".threeKindPerWin").text(<%= ((Game.where(final_player_hand_rank: "three of a kind").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "three of a kind").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "three of a kind").length + Game.where(final_computer_hand_rank: "three of a kind").length.to_f)*100).round(2).to_s %> + "%");


$(".twoPairNumber").text(<%=Game.where(final_player_hand_rank: "two pairs").length + Game.where(final_computer_hand_rank: "two pairs").length%>);
$(".twoPairPer").text(<%=(((Game.where(final_player_hand_rank: "two pairs").length.to_f + Game.where(final_computer_hand_rank: "two pairs").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".twoPairPerWin").text(<%= ((Game.where(final_player_hand_rank: "two pairs").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "two pairs").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "two pairs").length + Game.where(final_computer_hand_rank: "two pairs").length.to_f)*100).round(2).to_s %> + "%");


$(".onePairNumber").text(<%=Game.where(final_player_hand_rank: "one pair").length + Game.where(final_computer_hand_rank: "one pair").length%>);
$(".onePairPer").text(<%=(((Game.where(final_player_hand_rank: "one pair").length.to_f + Game.where(final_computer_hand_rank: "one pair").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".onePairPerWin").text(<%= ((Game.where(final_player_hand_rank: "one pair").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "one pair").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "one pair").length + Game.where(final_computer_hand_rank: "one pair").length.to_f)*100).round(2).to_s %> + "%");


$(".nothingNumber").text(<%=Game.where(final_player_hand_rank: "nothing").length + Game.where(final_computer_hand_rank: "nothing").length%>);
$(".nothingPer").text(<%=(((Game.where(final_player_hand_rank: "nothing").length.to_f + Game.where(final_computer_hand_rank: "nothing").length.to_f)/(Game.where.not(winner: nil).length*2).to_f)*100).round(2).to_s%> + "%");
$(".nothingPerWin").text(<%= ((Game.where(final_player_hand_rank: "nothing").where(winner: "player wins").length.to_f+Game.where(final_computer_hand_rank: "nothing").where(winner: "computer wins").length.to_f)/(Game.where(final_player_hand_rank: "nothing").length + Game.where(final_computer_hand_rank: "nothing").length.to_f)*100).round(2).to_s %> + "%");